---
title: ""
output:
  pdf_document: default
params:
  meeting: Meeting 1
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "latex")
library(knitr)
library(kableExtra)
library(flextable)
library(tidyverse)
library(scales)
library(qualtRics)
library(janitor)
usepackage_latex("booktabs")
usepackage_latex("longtable")
usepackage_latex("array")
usepackage_latex("multirow")
usepackage_latex("xcolor")
usepackage_latex("wrapfig")
usepackage_latex("float")
usepackage_latex("colortbl")
usepackage_latex("pdflscape")
usepackage_latex("tabu")
usepackage_latex("threeparttable")
usepackage_latex("threeparttablex")
usepackage_latex("ulem", "normalem")
usepackage_latex("makecell")

#evaluations <- read_survey(paste0(setwd(here::here()), "/sample_qualtrics_file.csv"))
#evaluations <- read_survey(paste0(setwd(here::here()), "/evaluations1.csv"))

evaluations_tidy <- evaluations %>%
  pivot_longer(
    -(StartDate:`Q1.1`), 
    names_to = c("meeting_number", "question"),
    # Use Q(number).(number) pattern to extract values
    names_sep = "\\.",
    values_to = "response", 
    values_drop_na = TRUE
  ) %>%
  mutate(
    meeting_number = as.numeric(gsub(x=meeting_number, pattern = "Q", replacement = ""))) %>% 
  # Remove last optional question
  filter(meeting_number!=max(meeting_number)) %>% 
  pivot_wider(names_from = "question", 
              values_from = "response", 
              names_prefix = "q") %>% 
  clean_names() %>% 
  rename(meeting = q1_1) %>% 
  arrange(meeting_number)%>% 
  mutate(meeting = gsub("&", "and", meeting))

pie_data <- evaluations_tidy %>% 
  filter(meeting==params$meeting) %>% 
  select(q3) %>% 
  na.omit() %>% 
  group_by(q3) %>% 
  summarise(n=n())

expectations_data <- evaluations_tidy %>% 
  filter(meeting==params$meeting) %>% 
  select(starts_with("q2")) %>% 
  gather(key = "key", value="value") %>% 
  na.omit() %>% 
  mutate(key = recode(key,q2_1="The networking aspect \nof this meeting...",
               q2_2="The educational component/\nresource sharing \nof this meeting...",
               q2_3="The effectiveness of \nthe facilitator(s)...",
               q2_4="The style/format \nof this meeting...",
               q2_5="The learning \nenvironment",
               q2_6="The value I received \nby attending this meeting...")) %>% 
  group_by(key, value) %>% 
  summarise(n=n()) %>% 
  mutate(value= factor(value, levels=c("Did Not Meet My Expectations", "Met My Expectations","Exceeded My Expectations")))

blank_theme <- theme_minimal()+
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid=element_blank(),
    axis.ticks = element_blank(),
    plot.title=element_text(size=14, face="bold")
  )
```

# Evaluation for `r params$meeting`

```{r, echo=FALSE}
ggplot(expectations_data, aes(x=value, y=n, fill=value))+
  geom_bar(stat="identity")+
  facet_wrap(~ key)+
  labs(x="", fill="")+
  scale_fill_manual(values=c("#9370DB", "#66023C","#DF73FF")) +
  blank_theme +
  theme(axis.text.x=element_blank(),legend.position="bottom")+
  geom_text(label=expectations_data$n)

```

# Would you attend a future meeting with this group?

```{r, echo=FALSE, out.height="3.0in"}
ggplot(data=pie_data, aes(x="", y=n, fill=q3))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start=0)+
  labs(title = "", fill="", x="", y="") +
  scale_fill_manual(values=c("#800080", "#DF73FF")) +
  blank_theme +
  theme(axis.text.x=element_blank(),legend.text=element_text(size=12)) +
  geom_text(aes(y = n/2 + c(0, cumsum(n)[-length(n)]), 
                label = paste0(n," (",percent(n/sum(pie_data$n)),")")), size=5)
```

# What did you find the most valuable aspects of this program?

```{r, echo=FALSE, comment=NA}
evaluations_tidy %>%
  filter(meeting==params$meeting) %>% 
  select(q4) %>% 
  na.omit() -> valuable

if (nrow(valuable)==0) {
  message("No feedback provided\n")
} else {
  valuable %>% 
    kable(col.names = NULL) %>% 
    kable_styling()%>% 
  column_spec(1, width = "45em")
}
```

# Do you have any suggestions for future programs? What topic(s) would you want to be on the agenda of the next meeting?

```{r, echo=FALSE, comment=NA}
evaluations_tidy %>%
  filter(meeting==params$meeting) %>% 
  select(q5) %>% 
  na.omit() -> suggestions 
  
if (nrow(suggestions)==0) {
  message("No feedback provided\n")
} else {
  suggestions %>% 
    kable(col.names = NULL)%>% 
    kable_styling()%>% 
  column_spec(1, width = "45em") 
}
```
